CREATE DATABASE IMOBILIARIA;
USE IMOBILIARIA;

CREATE TABLE `IMOVEIS`(
	`ID` INT NOT NULL,
    `NAME` CHAR(30) NOT NULL,
    `DESCRIPTION` CHAR(50) NOT NULL,
    `ROOM_NUMBERS` INT NOT NULL,
	`SELL_VALUE` FLOAT DEFAULT NULL,
    
    PRIMARY KEY `PROPERTY_NAME` (`NAME`)
);

SELECT * FROM `IMOVEIS`;
SELECT ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE FROM IMOVEIS;

INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(1, 'Casa Simples', 'Casa no bairro Alvorada', 1, 750);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(2, 'Apartamento', 'Apartamento no bairro Universitario', 2, 1000);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(3, 'Casa moderna', 'Casa no bairro Farroupilha', 2, 2500);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(4, 'Kit-Net', 'Kit-Net no bairro São Francisco', 1, 500);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(5, 'Duplex', 'Duplex no bairro Portal', 4, 4500);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(6, 'Casa Simples 2', 'Casa no bairro Cidade-Alta', 3, 900);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(7, 'Chalé', 'Chalé no bairro Alvorada', 2, 1200);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(8, 'Alojamento', 'Alojamento no bairro Floresta', 1, 320);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(9, 'Apartamento Pequeno', 'Apartamento no bairro Alvorada', 2, 600);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(10, 'Apartamento de Luxo', 'Apartamento no bairro São Francisco', 3, 3000);

